project:
  type: book

lang: es

book:
  title: "Introducción al análisis de datos espaciales"
  author: "Juan Pablo, Luz María y El Chino"
  date: "2025-05-13"
  chapters:
    - index.qmd
    - Caps/01-Introduccion.qmd
    - Caps/02-Exploratorio.qmd
    - Caps/03-Poisson.qmd
    #- Caps/04-Gaussiano.qmd
    - Caps/05-Ejemplo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    code-fold: true
    code-summary: "Código"
    html-math-method: mathjax

#  pdf:
#    documentclass: scrreprt



